#services:
#
#  smitweb:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 1909:8000  # port du serveur : port de l'application
#    volumes:
#      - .:/smitci-app/
#      - static_volume:/smitci-app/static
#      - media_volume:/smitci-app/media
#      - logs_volume:/smitci-app/static/logs  # Mount logs volume
#    env_file:
#      - ./.env
#    restart: always
#    depends_on:
#      - smitDB
#
#
#  smitDB:
#    image: postgis/postgis:16-3.4
#    restart: always
#    environment:
#      - POSTGRES_USER=ogah
#      - POSTGRES_PASSWORD=NEWdimension_MAC@24
#      - POSTGRES_DB=smitci
#      - PG_DATA=/data
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#  smitadminer:
#    image: adminer
#    restart: always
#    ports:
#      - 1910:8080
#    environment:
#      - ADMINER_DEFAULT_SERVER=smitDB
#
#
#networks:
#  smitci_default:
#    external: true
#
#volumes:
#  pgdata:
#    driver: local
#  static_volume:
#  media_volume:
#  logs_volume:
services:
  smitweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1909:8000  # Port mapping for server access
    volumes:
      - .:/smitci-app/                # Application code mount
      - static_volume:/smitci-app/static
      - media_volume:/smitci-app/media
      - logs_volume:/smitci-app/static/logs  # Mount for logs
    env_file:
      - ./.env                        # Environment variables
    restart: always
    depends_on:
      - smitDB

  smitDB:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      - POSTGRES_USER=ogah
      - POSTGRES_PASSWORD=NEWdimension_MAC@24
      - POSTGRES_DB=smitci
      - PG_DATA=/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  smitadminer:
    image: adminer
    restart: always
    ports:
      - 1910:8080  # Port mapping for Adminer
    environment:
      - ADMINER_DEFAULT_SERVER=smitDB  # Default DB server in Adminer

networks:
  smitci_default:
    external: true  # Ensure the network exists

volumes:
  pgdata:
    driver: local
  static_volume:
  media_volume:
  logs_volume:  # Volume for logs