services:

  smitweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1909:8000  # port du server : port de l'application
    volumes:
      - .:/smitci-app/
    env_file:
      - ./.env
    restart: always
    depends_on:
      - smitDB



  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - smitci_default

  adminer:
    image: adminer
    restart: always
    ports:
      - 1910:8080
    networks:
      - smitci_default

networks:
  smitci_default:
    external: true

volumes:
  pgdata:
    driver: local
  static_volume:
  media_volume: